Implement first version of registration - WIP
dbrgn/flugbuech pull request #92
Opened 2021-08-12 21:17 UTC by Liberatys

2021-08-12 21:19 UTC, Liberatys commented on src/data.rs
> +const MAX_PASSWORD_LENGTH: i32 = 30;
RANDOM 😆

2021-08-15 22:47 UTC, dbrgn commented
Oh, cool! This was on my TODO list for a long time.

I'll try to take a look soon-ish. If I should forget, feel free to ping me!

2021-08-16 09:28 UTC, Liberatys commented
Havent written a lot of Rust recently 😂 so I'll refactor it once I have the time. 

Don't know your view on required unique email? Doesn't have to be 🙃

2021-09-12 13:16 UTC, dbrgn requested changes
Hi, since I can't fly for two weeks, I finally got around to reviewing your PR 😄

I left a few comments. The main issue is that control flow can be improved by using more idiomatic `Result` based validation, instead of checking boolean flags.

2021-09-12 13:16 UTC, dbrgn commented on src/data.rs
> +) -> (bool, String) {
Instead of working with a `(bool, String)` pair, I'd use a `Result` instead:

```rust
enum RegistrationError {
    /// E-Mail is invalid or already registered
    InvalidEmail,
    /// Username is invalid or already taken
    NonUniqueUsername,
    /// The password confirmation does not match
    PasswordConfirmation,
}
```

Then, return `Result<(), RegistrationError>`. If you get back an `Ok(())`, the registration was valid.

This has the advantage, that the validation functions can now return the same type (return `Ok(())` if the validation passes, or return an `Err(RegistrationError)` instead). This way, you can call them with the question mark:

```rust
if password_confirmation != password {
    return Err(RegistrationError::PasswordConfirmation);
}
validate_email(email)?;
validate_password_format(password)?;
// ...and so on

// At the end
Ok(())
```

2021-09-12 13:16 UTC, dbrgn commented on src/data.rs
> +fn validate_email(email: &str) -> bool {
Note: Properly validating e-mail addresses with RegEx is really hard. You easily end up with valid addresses being rejected, or with RegExes that are subject to [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html).

In general, I prefer to use a very simple validation step, and then sending a confirmation e-mail before unlocking the account. If it cannot be delivered, then we already know that it's invalid.

For now we don't send a confirmation e-mail (which is OK as a first, rough registration workflow), but I still think we can reduce the validation regex to this: `^[^@\s]+@[^@\s]+\.[^@\s]+$` (see https://stackoverflow.com/a/742588/284318).

2021-09-12 13:16 UTC, dbrgn commented on templates/login.tera
> +    <a href="/auth/registration">Don't have an account yet? Register a new account</a>
Maybe a slight rewording?

```suggestion
    <p>Don't have an account yet? <a href="/auth/registration">Register now!<a></p>
```

2021-09-12 13:16 UTC, dbrgn commented on templates/registration.tera
> +            <input class="input" type="text" name="username" id="username" value="" required />
Note: In HTML5 you don't need self-closing tags like ` />` (because it's not XML). Just use a plain `<input ...>` tag. (Some more cases are further below.)

2021-09-12 15:25 UTC, dbrgn requested changes
This is looking good, thanks for the quick updates! I have left a few more comments, then I think this could be merged. Feel free to mark the PR as "ready for review", so that CI can run.

2021-09-12 15:25 UTC, dbrgn commented on templates/registration.tera
> +            <input class="input" type="password" name="password" id="password" value="" required>
Can you add the `minlength="8"` attribute to this input field (and the next one)? Ideally the length value is passed in from the handler through the context.

Additionally, a placeholder text would be helpful (`placeholder="Choose a password (at least n characters)"`).

2021-09-12 15:25 UTC, dbrgn commented on templates/login.tera
> +    <p>Don't have an account yet? <a href="/auth/registration">Register now!<a></p>
In addition to the login template, could you update the section `Can I sign up?` in `index.tera`? Maybe something like `Yes, feel free to <a href="...">create an account</a>!`.

2021-09-12 15:25 UTC, dbrgn commented on src/auth.rs
> +            Ok(Redirect::to("/"))
Maybe the success case could add a flash message as well? Something like "Your registration has been processed, welcome!".

(Note: For that, the success case needs to return the type `Flash<Redirect>` as well.)

2021-09-12 20:36 UTC, Liberatys commented on src/data.rs
> +}
I'd be happy to add them in a separate pr? If that is okay for you :D

2021-09-12 21:02 UTC, Liberatys commented on src/data.rs
> +// TODO: extend with proper format check
maybe for later ^^ you know :D "Must contain capital letter, must contain special character" 😉  Das ganze Spiel

2021-09-12 21:05 UTC, Liberatys commented
Thank you for taking the time to review the pull request :D (multiple times 🤦🏻)! Much appreciate 🙏🏻

2021-09-12 21:36 UTC, dbrgn commented on src/data.rs
> +// TODO: extend with proper format check
👍🏻 Yeah, we could do that sometime. Although finding good metrics is really hard. Another option would be checking against the https://haveibeenpwned.com/ database. But it's not really a sensitive website, so let's keep it simple for now 🙂

2021-09-12 21:37 UTC, dbrgn commented on src/data.rs
> +}
Sure, that sounds good! 👍🏻

2021-09-12 21:46 UTC, dbrgn approved these changes
Hm, seems that I didn't enable PR checking in CI. I fixed that now on `master`, but for this PR I ran the tests manually and they pass. Let's merge without rebasing. Thanks @Liberatys!

2021-09-12 21:47 UTC, merged